import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // Ignore build output, deps, generated dirs, and tooling artifacts so typed
  // lint rules (which need a matching tsconfig entry) never run on them.
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "drizzle/**",
      "playwright-report/**",
      "test-results/**",
      // next-env.d.ts is regenerated by `next build`; its triple-slash
      // reference is intentional and must not be linted.
      "next-env.d.ts",
      // runtime/cache/vendor-skill areas (AGENTS.md) — never linted.
      ".omo/**",
      ".screenshots/**",
      ".playwright-mcp/**",
      ".agents/**",
      ".opencode/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // Non-type-checked rules apply to every linted file (ts/tsx/js/cjs/mjs).
    rules: {
      // Codebase convention: `_`-prefixed params/vars/caught-errors are
      // intentionally unused (e.g. mock stubs, catch blocks that retry).
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // Type-checked rules require parserOptions.project so the TS parser can
    // resolve types. `project: true` makes each file use its nearest tsconfig.
    // Scope to .ts/.tsx: .mjs/.cjs configs and other non-TS files have no
    // tsconfig entry and cannot participate in type-aware linting.
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: { project: true },
    },
    rules: {
      // Catch dropped async values (server actions, revalidatePath, etc.) — a
      // common source of silent unhandled rejections in App Router handlers.
      "@typescript-eslint/no-floating-promises": "error",
      // Flag pointless `async` functions that never `await`, which usually
      // signals a forgotten await in real handler code.
      "@typescript-eslint/require-await": "error",
    },
  },
  {
    // Test files legitimately use the `async () => syncValue` mock pattern to
    // satisfy Promise-returning signatures (vi.fn, lazy thunks, repository
    // stubs) without awaiting inside. require-await fires ~265 false positives
    // on this idiomatic mock style and is muted here; no-floating-promises
    // still guards genuine unhandled rejections in tests.
    files: ["**/*.test.ts", "**/*.test.tsx", "src/test/**"],
    rules: {
      "@typescript-eslint/require-await": "off",
    },
  },
];

export default eslintConfig;
