-- 0003b_fk_tenant_scoping.sql
-- Tenant-scoped foreign keys for the rombongan_belajar tables (cubic P1 fixup).
--
-- Defense in depth on top of the action-layer existence checks. The 0003
-- migration created single-column FKs (penempatan.rombongan_belajar_id →
-- rombongan_belajar(id), penempatan.tahun_ajaran_id → tahun_ajaran(id)). A
-- single-column FK cannot reject a cross-tenant id: tenant-A's penempatan row
-- could legally point at tenant-B's rombel/TA uuid. RLS makes such reads
-- invisible and the new action checks throw before insert, but the FK itself
-- should also enforce tenant co-residency so a future caller that forgets
-- withTenant cannot corrupt integrity.
--
-- Approach:
--   1. Add composite UNIQUE (tenant_id, id) on rombongan_belajar, tingkat, and
--      tahun_ajaran (required as FK targets; (id) PK already guarantees these
--      are unique, the UNIQUE exists solely to be referenceable).
--   2. Drop the single-column FKs from penempatan_rombongan_belajar that point
--      at rombongan_belajar and tahun_ajaran.
--   3. Recreate them as composite (tenant_id, <fk>) → parent(tenant_id, id),
--      preserving ON DELETE CASCADE.
--
-- Idempotent: UNIQUE indexes use IF NOT EXISTS; FK drops use a constraint-name
-- introspection loop; FK adds are guarded by an IF-NOT-EXISTS DO block.

-- 1. Composite UNIQUE (tenant_id, id) — FK targets for tenant-scoped composite FKs.
create unique index if not exists rombongan_belajar_tenant_id_unique
  on rombongan_belajar (tenant_id, id);
create unique index if not exists tingkat_tenant_id_unique
  on tingkat (tenant_id, id);
create unique index if not exists tahun_ajaran_tenant_id_unique
  on tahun_ajaran (tenant_id, id);

-- 2. Drop the single-column FKs from penempatan_rombongan_belajar that target
--    rombongan_belajar / tahun_ajaran (names are auto-generated by Postgres, so
--    discover them rather than hard-coding).
do $$
declare
  r record;
begin
  for r in
    select con.conname
    from pg_constraint con
    where con.conrelid = 'penempatan_rombongan_belajar'::regclass
      and con.contype = 'f'
      and con.confrelid in (
        'rombongan_belajar'::regclass,
        'tahun_ajaran'::regclass
      )
  loop
    execute format(
      'alter table penempatan_rombongan_belajar drop constraint if exists %I',
      r.conname
    );
  end loop;
end $$;

-- 3. Recreate as composite, tenant-scoped FKs (preserving ON DELETE CASCADE).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'penempatan_rombongan_belajar'::regclass
      and conname = 'penempatan_rombel_tenant_fk'
  ) then
    alter table penempatan_rombongan_belajar
      add constraint penempatan_rombel_tenant_fk
        foreign key (tenant_id, rombongan_belajar_id)
        references rombongan_belajar (tenant_id, id)
        on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'penempatan_rombongan_belajar'::regclass
      and conname = 'penempatan_tahun_ajaran_tenant_fk'
  ) then
    alter table penempatan_rombongan_belajar
      add constraint penempatan_tahun_ajaran_tenant_fk
        foreign key (tenant_id, tahun_ajaran_id)
        references tahun_ajaran (tenant_id, id)
        on delete cascade;
  end if;
end $$;

comment on constraint penempatan_rombel_tenant_fk on penempatan_rombongan_belajar is
  'Tenant-scoped composite FK: a penempatan row must reference a rombongan_belajar in the SAME tenant (defense in depth against cross-tenant id injection).';
comment on constraint penempatan_tahun_ajaran_tenant_fk on penempatan_rombongan_belajar is
  'Tenant-scoped composite FK: a penempatan row must reference a tahun_ajaran in the SAME tenant (defense in depth against cross-tenant id injection).';
